NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org2.kevin.kongyixueyuan.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org2.kevin.kongyixueyuan.com-cert.pem
    OrganizationalUnitIdentifier: peer
